// Charcoal products imported from thehookahshop.com (white background images only)
import { Product } from "./products";

export const charcoalProducts: Product[] = [
  {
    id: 'char-1',
    name: 'Coco Fuego Hexagon',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-hexagon.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-2',
    name: 'Coco Fuego Bermuda (Triangle)',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-bermuda.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-3',
    name: 'Coco Fuego Half Moon',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-half-moon.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-4',
    name: 'Coco Fuego Cubes',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-cubes.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-5',
    name: 'Coco Fuego Flower Cubes XL',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-flower-cubes-xl.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-6',
    name: 'Coco Fuego Quarter Circle',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-quarter-circle.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-7',
    name: 'Large Starbuzz Charcoal 40mm',
    brand: 'Starbuzz',
    price: 23.99,
    salePrice: 20.99,
    category: 'charcoal',
    image: '/images/charcoal/large-starbuzz-charcoal-40mm.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-8',
    name: 'Coco Fuego Big Boss Cubes',
    brand: 'Coco Fuego',
    price: 17.99,
    salePrice: 14.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-fuego-big-boss-cubes.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-9',
    name: 'Titanium Cubettes',
    brand: 'Titanium',
    price: 15.99,
    salePrice: 13.99,
    category: 'charcoal',
    image: '/images/charcoal/titanium-cubettes.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-10',
    name: 'Charco Flare Cubes',
    brand: 'Charco Flare',
    price: 21.99,
    salePrice: 19.99,
    category: 'charcoal',
    image: '/images/charcoal/charco-flare-cubes.webp',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'char-11',
    name: 'Coco Nara Coconut Shell Charcoal',
    brand: 'Coco Nara',
    price: 14.99,
    salePrice: 12.99,
    category: 'charcoal',
    image: '/images/charcoal/coco-nara-coconut-shell-charcoal.webp',
    badge: 'SALE',
    inStock: true,
  },
];
