// Terms and Conditions Page
// Includes Google Analytics disclosure and privacy policy compliance

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-1 py-12">
        <div className="container max-w-4xl">
          <h1 className="text-4xl font-display font-black mb-8">Terms & Conditions</h1>
          
          <div className="prose prose-lg max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
              <p className="mb-4">
                By accessing and using this website, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use this website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">2. Age Verification</h2>
              <p className="mb-4">
                You must be of legal age (18+ or 21+ depending on your jurisdiction) to purchase tobacco products. By using this website, you confirm that you meet the age requirements in your location. Age verification may be conducted by a third-party service at checkout.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">3. Product Information</h2>
              <p className="mb-4">
                All products sold on this website contain nicotine. <strong>Nicotine is an addictive chemical.</strong> Product descriptions, images, and specifications are provided for informational purposes and may be subject to change without notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">4. Privacy Policy & Data Collection</h2>
              
              <h3 className="text-xl font-semibold mb-3 mt-6">Google Analytics</h3>
              <p className="mb-4">
                This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies" (text files placed on your computer) to help analyze how users interact with our site.
              </p>
              <p className="mb-4">
                The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage.
              </p>
              <p className="mb-4">
                You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website.
              </p>

              <h3 className="text-xl font-semibold mb-3 mt-6">Information We Collect</h3>
              <p className="mb-4">
                We collect information you provide directly to us, such as when you create an account, place an order, or contact customer service. This may include:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Name, email address, phone number</li>
                <li>Billing and shipping addresses</li>
                <li>Payment information (processed securely through third-party payment processors)</li>
                <li>Order history and preferences</li>
                <li>Communications with customer support</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3 mt-6">How We Use Your Information</h3>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Process and fulfill your orders</li>
                <li>Communicate with you about your orders and account</li>
                <li>Send promotional emails (you may opt out at any time)</li>
                <li>Improve our website and customer experience</li>
                <li>Comply with legal obligations and age verification requirements</li>
                <li>Detect and prevent fraud</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3 mt-6">GDPR Compliance (European Users)</h3>
              <p className="mb-4">
                If you are located in the European Economic Area (EEA), you have certain data protection rights under the General Data Protection Regulation (GDPR):
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li><strong>Right to Access:</strong> You can request a copy of your personal data</li>
                <li><strong>Right to Rectification:</strong> You can request correction of inaccurate data</li>
                <li><strong>Right to Erasure:</strong> You can request deletion of your personal data</li>
                <li><strong>Right to Restrict Processing:</strong> You can request limitation of how we use your data</li>
                <li><strong>Right to Data Portability:</strong> You can request transfer of your data to another service</li>
                <li><strong>Right to Object:</strong> You can object to processing of your personal data</li>
              </ul>
              <p className="mb-4">
                To exercise these rights, please contact us at the email address provided below.
              </p>

              <h3 className="text-xl font-semibold mb-3 mt-6">CCPA Compliance (California Residents)</h3>
              <p className="mb-4">
                If you are a California resident, the California Consumer Privacy Act (CCPA) provides you with specific rights regarding your personal information:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li><strong>Right to Know:</strong> You can request information about the personal data we collect, use, and share</li>
                <li><strong>Right to Delete:</strong> You can request deletion of your personal information</li>
                <li><strong>Right to Opt-Out:</strong> You can opt-out of the sale of your personal information (we do not sell personal information)</li>
                <li><strong>Right to Non-Discrimination:</strong> We will not discriminate against you for exercising your CCPA rights</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3 mt-6">Cookies and Tracking Technologies</h3>
              <p className="mb-4">
                We use cookies and similar tracking technologies to track activity on our website and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">5. Shipping & Returns</h2>
              <p className="mb-4">
                Shipping times and costs vary by location. We ship to addresses within the United States only. Due to the nature of tobacco products, returns are subject to specific conditions and may not be accepted for opened products. Please review our full return policy before making a purchase.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">6. Pricing & Payment</h2>
              <p className="mb-4">
                All prices are in USD and are subject to change without notice. We accept major credit cards and other payment methods as displayed at checkout. Payment information is processed securely through third-party payment processors and is not stored on our servers.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">7. Intellectual Property</h2>
              <p className="mb-4">
                All content on this website, including text, graphics, logos, images, and software, is the property of Boss Hookah Wholesale or its content suppliers and is protected by copyright and trademark laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">8. Limitation of Liability</h2>
              <p className="mb-4">
                To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the website or products.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">9. Changes to Terms</h2>
              <p className="mb-4">
                We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting to the website. Your continued use of the website after changes are posted constitutes acceptance of the modified terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">10. Contact Information</h2>
              <p className="mb-4">
                If you have questions about these Terms & Conditions, our Privacy Policy, or wish to exercise your data protection rights, please contact us at:
              </p>
              <p className="mb-2">
                <strong>Email:</strong> support@bosshookahwholesale.com
              </p>
              <p className="mb-4">
                <strong>Response Time:</strong> We aim to respond to all inquiries within 48 hours.
              </p>
            </section>

            <section className="border-t pt-6 mt-8">
              <p className="text-sm text-muted-foreground">
                <strong>Last Updated:</strong> February 6, 2026
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                By using this website, you acknowledge that you have read and understood these Terms & Conditions and our Privacy Policy.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
